### PR TITLE
Throw user-visible error on opening a dataset which is too large to visualize

### LINKED ISSUE #466: Problem Opening Very Long Table
# Description

It looks like HDFView is unable to open very long tables.

# Steps to Reproduce

1. Open a file that contains three column table with a length of `340 205 976` values (according to the output of `h5dump --header`)
2. Double click on the table

# Expected Result

HDFView opens the table (after some time) or informs me that the table is too large to open/display.

# Actual Result

HDFView opens a dialog that shows the error message:

```
Error occurred while instantiating TableView class
```

Image

# Additional Information

## Header Data

```
HDF5 "Documents/Battery Discharge.hdf5" {
GROUP "/" {
   ATTRIBUTE "CLASS" {
      DATATYPE  H5T_STRING {
         STRSIZE 5;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "FILTERS" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SCALAR
   }
   ATTRIBUTE "PYTABLES_FORMAT_VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE 3;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "TITLE" {
      DATATYPE  H5T_STRING {
         STRSIZE 20;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE 3;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   DATASET "acceleration" {
      DATATYPE  H5T_COMPOUND {
         H5T_STD_U8LE "counter";
         H5T_STD_U64LE "timestamp";
         H5T_IEEE_F32LE "x";
      }
      DATASPACE  SIMPLE { ( 340205976 ) / ( H5S_UNLIMITED ) }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 5;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_0_FILL" {
         DATATYPE  H5T_STD_U8LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_0_NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 7;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_1_FILL" {
         DATATYPE  H5T_STD_U64LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_1_NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 9;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_2_FILL" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "FIELD_2_NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 1;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "NROWS" {
         DATATYPE  H5T_STD_I64LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "Sensor_Range" {
         DATATYPE  H5T_STRING {
            STRSIZE 13;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "Start_Time" {
         DATATYPE  H5T_STRING {
            STRSIZE 26;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "TITLE" {
         DATATYPE  H5T_STRING {
            STRSIZE 21;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "VERSION" {
         DATATYPE  H5T_STRING {
            STRSIZE 3;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
   }
}
}
```

### PR DESCRIPTION
**Pull request by mattjala**
When a dataset dimension is large enough along one axis that the number of elements times the number of pixels per cell overflows a Java int (~2.1B limit), NatTable/SWT breaks - the table window opens with headers but no data rows without throwing an error. This can be replicated with a dataset with \~340M rows ( * 24 pixels vertically =\~ 2.1B) or \~26M columns (* 80 pixels horizontally =\~ 2.1B).

Since the error exists in an underlying library and outside of our power to easily fix, I've added checks to detect this case and throw a user-visible error instead of silently failing. 

Resolves #466

----

> [!IMPORTANT]
> Adds checks in `Dataset.java` to prevent overflow errors when visualizing large datasets, and updates Maven plugin versions.
> 
>   - **Behavior**:
>     - Adds checks in `getData()` in `Dataset.java` to throw an exception if dataset dimensions exceed `MAX_DISPLAY_ROWS` or `MAX_DISPLAY_COLS`.
>     - Displays user-visible error when dataset is too large to visualize.
>   - **Constants**:
>     - Defines `MAX_DISPLAY_ROWS` and `MAX_DISPLAY_COLS` in `Dataset.java` to limit dataset dimensions for display.
>   - **Build**:
>     - Updates `maven-resources-plugin` version to `3.3.1` in `object/pom.xml` and `pom.xml`.
>     - Changes resource directory path in `pom.xml`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=HDFGroup%2Fhdfview&utm_source=github&utm_medium=referral)<sup> for 8e22c09e76b43a2ff8169489d87b98e1db284674. You can [customize](https://app.ellipsis.dev/HDFGroup/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: object/src/main/java/hdf/object/Dataset.java [hunk 1]
```diff
@@ -660,6 +664,17 @@ public Object getData() throws Exception, OutOfMemoryError
     {
         log.trace("getData(): isDataLoaded={}", isDataLoaded);
         if (!isDataLoaded) {
+            long displayRows = selectedDims[selectedIndex[0]];
+            long displayCols = (rank > 1) ? selectedDims[selectedIndex[1]] : 1;
+            if (displayRows > MAX_DISPLAY_ROWS) {
+                throw new Exception("Too many rows to display (" + displayRows + " rows, limit is " +
```
Comment (jhendersonHDF) [inline object/src/main/java/hdf/object/Dataset.java]: This is something that should be fixed at the tableview abstraction level, not the object library Dataset abstraction level.

File: object/src/main/java/hdf/object/Dataset.java [hunk 2]
```diff
@@ -47,6 +47,10 @@ public abstract class Dataset extends HObject implements DataFormat {
 
     private static final Logger log = LoggerFactory.getLogger(Dataset.class);
 
+    // SWT uses int pixel coordinates; dimension * pixelsPerCell overflows int, silently breaking display.
+    public static final long MAX_DISPLAY_ROWS = 80_000_000L; // ~89M at 24px row height
+    public static final long MAX_DISPLAY_COLS = 25_000_000L; // ~26M at 80px column width
```
Comment (jhendersonHDF) [inline object/src/main/java/hdf/object/Dataset.java]: This seems way too fragile to hard code a limit to check for

Comment (mattjala) [reply object/src/main/java/hdf/object/Dataset.java]: In what sense? The pixel values aren't exact, but at least for columns it's hard to imagine a user wanting much less than 24px in height per row. The columns might vary more for datasets with large numeric data, but in that case the columns would be wider than expected, causing this check to be useless (since we hit the int limit on pixel size sooner than ~25M columns) but not actively harmful

Comment (jhendersonHDF) [reply object/src/main/java/hdf/object/Dataset.java]: I think making predictions here based on pixel count will only get us into trouble; I could easily see the row and column sizes going in either direction. Based on https://github.com/eclipse-nattable/nattable/wiki/FAQ#how-much-data-can-you-put-behind-it, I think it would be better to simply check the number of rows and columns against 32-bit sizes and simply do not try to throw errors for any conditions outside of that. Any remaining problems are a downstream issue that we must accept, possibly updating to a newer version of the NATTable if available or filing a bug.

Comment (mattjala) [reply object/src/main/java/hdf/object/Dataset.java]: If I understand you correctly, a direct row/col check against the 32-bit limit would leave a pretty large range of sizes where HDFView still fails to display with no error message (between 25M-2.1B columns or 80M-2.1B rows). Maybe it's not truly HDFView's responsibility to worry about this, but it's a case real users have run into and it's fairly easy to check and give a useful error. On top of that, it doesn't seem like NatTable is likely to change this in the short-to-medium term (and if it were, it would take time to propagate the version update into HDFView anyway).

Comment (jhendersonHDF) [reply object/src/main/java/hdf/object/Dataset.java]: > If I understand you correctly, a direct row/col check against the 32-bit limit would leave a pretty large range of sizes where HDFView still fails to display with no error message (between 25M-2.1B columns or 80M-2.1B rows).

Correct, but I would treat this as a downstream problem to be reported, as there is no good way we're going to be able to predict based off of pixel sizes.

> On top of that, it doesn't seem like NatTable is likely to change this in the short-to-medium term (and if it were, it would take time to propagate the version update into HDFView anyway).

Maybe, but NatTable still seems to be under active development (https://github.com/eclipse-nattable/nattable), so we could easily (excepting source changes that may need to be made) update to a newer version and try this again. Or at least report an issue.
